import { signInUserService, signUpUserService } from "../services/userServices.js";


export const getuserProfile = async (req,res)=>{
    res.json({
        message: "this is dummy implementation of the userProfiel",
    })
};



export const signUp = async (req, res)=>{
    try{
        const user = await signUpUserService(req.body);
        return res.status(201).json({
            success:true,
            message:"User created Successfully",
            data:user,
        })
    }
    catch(error){
        // console.log(error);
        // console.log("error name:",error.name);
        // console.log("error code", error.code);
        if(error.status){// this means that error is already having a status key this means it is a custom error generated by us
            return res.status(error.status).json({
                success:false,
                message:error.message,
            })
        }
        res.status(500).json({
            sccess:false,
            message:"internal server error",

        })
    }
}

export const signIn = async(req,res)=>{
    try{
        const response = await signInUserService(req.body);
        return res.status(200).json({
            sucess:true,
            message:"user signedIn successfully",
            data: response,
        });

    }catch(error){
        if(error.status){// this means that error is already having a status key this means it is a custom error generated by us
            return res.status(error.status).json({
                success:false,
                message:error.message,
            })
        }
        res.status(500).json({
            sccess:false,
            message:"internal server error",
            error:error,

        })
    }
}